site_name: Introduction to FRC
site_url: https://zzhangje.github.io/intro2frc/
repo_url: https://github.com/zzhangje/intro2frc
edit_uri: edit/master/docs/

nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Resources: resources.md
  - News: blog/index.md
  - Gallery: gallery.md

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: icon/frc6399.ico
  # logo: icon/frc6399.ico
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.sidebar
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.image.lightbox
    - content.card
    - content.action.edit

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition

plugins:
  - blog:
      blog_toc: true
      post_dir: news

extra_javascript:
  - https://unpkg.com/masonry-layout@4.2.2/dist/masonry.pkgd.min.js
  - js/init-gallery.js

extra_css:  
  - css/extra.css

extra:
    base_path: /intro2frc
    social:
      - icon: fontawesome/brands/weixin
        link: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzAxOTgzNjI3MQ==&scene=124#wechat_redirect
    