authors:
  jerry:
    name: Jerry Zhang
    description: Program Mentor
    avatar: /icon/jerry.jpg
  casper:
    name: Casper Chang
    description: Team Captain
    avatar: /icon/casper.jpg
  verity:
    name: Verity Xie
    description: Lead Coach
    avatar: /icon/shit.png